### ISSUE TITLE
Where to implement complementary endpoints?

### ISSUE THREAD

**Issue by cyrlop** [bedapub/metadata-registration-api#14]
Hi @molitoris 

Could I get your opinion on the following?
People need more API endpoints to achieve the following:

1. Get study data in FORM format
2. Post study data in FORM format 
3. Endpoint to get a dataset or a processing event directly (without passing the study ID or dataset ID) --> See new endpoints I added in `api_study.py`

Points 1. and 2. are usefull so people from any language could easily upload/get studies or datasets an extra library 

My question is "where do you see these endpoints?"

- Option 1: Add endpoints to this API  
I could add an "input_format" parameter to existing routes for 1. and 2.
I know you said supporting one format is better :)
- Option 2: Do a separate "helper" API
- Option 3: Implement some of these routes in the UI flask app
- Option 4: Use Elastic Search (since everything should be indexed in FORM format)

**Comment by molitoris** [comment]
Hi @cyrlop 

Thank you for reaching out.

There is a general challenge to implementing endpoints in form format. To my knowledge, the flask-restx library does not allow you to define models with variable names. Thus, the api format has fixed names (property and value):

```json
"entries": [
		{"property": <id>, "value": <value>},
		{"property": <id>, "value": <value>},
		...
	],
```

This is the main reason why there are two formats (form and api). I am not sure how easy it is to implement 1 & 2. If possible, I would tend to option 1. As I don't see a good solution, it is hard to give you good advice.

3: Dataset seems to be a top-level datatype. If this is the case, you should create a separate collection and the corresponding endpoints. However, I don't get how you want to retrieve a dataset if you don't know its identifier. If an end-user wants to manually search for a dataset, you should provide a search function in the UI (The UI will still use a identifier in the background).

**Comment by cyrlop** [comment]
Thanks for your reply @molitoris,

**1. and 2. -->** I think it's easy to implement option 1.

- For POSTing: you don't use flask-restx models, we could just add an `entry_format` flag (default to `api`)
- For GETting: the only reason you use flask-restx model is to serialize objects (here Study) to Json.  
At the moment you are doing that using the `@api.marshal_with(study_model)` decorator but you can as well directly call `marshal(study, study_model)` in the method.

Here is an example of what I could do:
Current code:
```python
    @api.marshal_with(study_model_id)
    def get(self, id):
        """Fetch an entry given its unique identifier"""
        return Study.objects(id=id).get()
```
New code:
```python
    def get(self, id):
        """Fetch an entry given its unique identifier"""
        study = Study.objects(id=id).get()
        study_json = marshal(study, study_model)

        if entry_format == "api":
            return study_json

        elif entry_format == "form":
            prop_map = get_property_map(key="id", value="name")
            study_converter = FormatConverter(prop_map).add_api_format(study_json["entries"])
            study_json["entries"] = study_converter.get_form_format()

            return study_json
```
Then `entry_format` could be either passed via arg_parser or via new URLs like that:

```python
@api.route("/id/<id>")
@api.route("/id/<id>/")
@api.route("/id/<id>/<entry_format>")
@api.param("id", "The property identifier")
class ApiStudy(Resource):
    def get(self, id, entry_format="api"):
      # Do stuff
```
Does it make sense?

**3. -->** The whole point is that dataset (and maybe others) are not top level, but nested entries under study
I already have endpoints like this: `/id/<study_id>/datasets/id/<dataset_uuid>` but some would like `/id/<dataset_uuid>` directly. Not a gig deal for that one.

**Comment by molitoris** [comment]
@cyrlop 

**1. & 2. -->** I like to idea of the `marshal` within the get request. I would make `entry_form` a query parameter (e.g. `study/1?entry_format=api`). What would be the advantage of a template parameter (e.g. `study/1/api`)? Is it possible to show the form format in the swagger documentation? 

**3. -->** I found some suggestion on how to do this in the mongo shell (see [here](https://stackoverflow.com/questions/32739734/mongodb-get-all-elements-of-a-nested-array), [here ](https://stackoverflow.com/questions/32733388/elegant-list-of-repeated-sub-items)or [here](https://stackoverflow.com/questions/32716677/mongodb-list-projection-of-subfield)). However, I am not sure that MongoEngine supports any of those commands. If it works, you might want to index the dataset to boost performance.

**Comment by cyrlop** [comment]
@molitoris,

**1. & 2. -->** I have no idea which is better, I'm ok with query parameters but do this work for post/put as well?
Anyway, I was wrong I forgot that you use flask-restx models in each post/put as well: `@api.expect(study_add_model)` so your first concern still applies. I'll look into a solution.

**3. -->** I don't think we're talking about the same thing, I already have endpoints with study_id>dataset_id I just need one with only dataset_id (that would kind of find the study_id and redirect to the other endoint)
But forget about 3. that's another issue 😃

**Comment by cyrlop** [comment]
GET: `@api.marshal_with()` has the advantage of providing the swagger doc so if I implement the previous comment, we loose the part in swagger that shows the expected output.

POST: `@api.expect()` provides documentation for the expected input in swagger, but does not perform validation (by default) so the only advantage of having it is for swagger documentation.

It looks like both `@api.marshal_with()` and `@api.expect()` are only useful for documenting, I'll look if we can manually set the documentation (so we could show both api and form format). I know it sounds dirty but form format GET and POST are key feature when it comes to people using the API.

Worst case scenario I can implement these routes in another app (ex: flask UI) that would basically do the conversion and call the API in api format.

Another option is to do completely new routes with "/form_format/xxx" for example but I don't like this idea.

**Comment by cyrlop** [comment]
- :heavy_check_mark: Figure out how to document 2 models in swagger (GET): Use 2 `@api.response()` status
- :warning: Figure out how to document 2 models in swagger (POST): Added "entry_format" in expected model (the swagger exemple will be with api format only)
- :heavy_check_mark: Figure out why parser parameters don't show up on swagger UI: Used `@api.doc(parser)` instead of `@api.expect(parser)`
- :heavy_check_mark: Clean endpoints with trailing slashes showing up twice: Used `strict_slashes=False`
- :heavy_check_mark: Fixed multiple swagger operations opening/closing simultaneously: Updated class names

**Comment by cyrlop** [comment]
Committed and merged, you can take a look the swagger looks and feels nicer 😃 Thanks for your input!
All test pass, but I don't test for the new form format option

**Comment by molitoris** [comment]
Just skipped through the code. Look very clean to me 👍. I like the way you perform one task per git commit. Makes it easy understandable.
