### ISSUE TITLE
Nested FieldList/FormFields don't get validated

### ISSUE THREAD

**Issue by cyrlop** [bedapub/metadata-registration-api#6]
The nested FieldList/FormFields don't get validated when study entries are uploaded. This is due to how the "input" format is converted to the "form" format in `api_utils.json_input_to_form_format()`.

For exemple, if prop_1 is a FieldList of FormFields, the following "input" format:
```
entry = {
    prop: prop_id_1
    value: [
        {
            prop: prop_id_1bis
            value: [
                {prop: prop_id_2, value: abc},
                {prop: prop_id_2, value: abc}
            ]
        },
        {
            prop: prop_id_1bis
            value: [
                {prop: prop_id_2, value: abc},
                {prop: prop_id_2, value: abc}
            ]
        }
    ]
}
```
is converted to the following "form" format:
```
entry = {
    prop_name_1: [
        {
            prop_name_1bis: {
                prop_id_2: abc,
                prop_id_2: abc
            }

        },
        {
            prop_name_1bis: {
                prop_id_2: abc,
                prop_id_2: abc
            }
        },
    ]
}
```
instead of:
```
entry = {
    prop_name_1: [
        {
            prop_id_2: abc,
            prop_id_2: abc
        },
        {
            prop_id_2: abc,
            prop_id_2: abc
        }
    ]
}
```
For the validation form to be populated correctly, the middle property `prop_name_1bis` must be skipped.

**Comment by cyrlop** [comment]
Waiting input from R. before going forward, this might break some logic.

**Comment by molitoris** [comment]
Hi @cyrlop 

I reproduced the reported issue. With the example below, I now understand your point. However, I do not remember why I included the middle property but I agree that we should change the behavior.

I see two possible approaches:
* Remove the 1bis property completely from the entry format
* Adapt the converter `json_input_to_form_format` to automatically remove the 1bis property

What do you think?

**Minimal Example**
```python
from wtforms import Form
from wtforms.fields import *
from wtforms.validators import DataRequired

from metadata_registration_api.api.api_utils import json_input_to_form_format


class Contact(Form):
    name = StringField()
    phone = StringField(validators=[DataRequired()])


class AddressBook(Form):
    title = StringField()
    contacts = FieldList(FormField(Contact))


if __name__ == '__main__':

    json_input = [
        {
            "prop": "4",
            "value": "Business Contacts"
        },
        {
            "prop": "1",  # contacts
            "value": [
                {
                    "prop": "1bis",  # contact
                    "value": [
                        {"prop": "2", "value": "Rafael"},  # name
                        {"prop": "3", "value": "079 000 00 00"}  # phone
                    ]
                },
                {
                    "prop": "1bis",  # contact
                    "value": [
                        {"prop": "2", "value": "Cyril"},  # name
                        {"prop": "3", "value": "079 111 11 11"}  # phone
                    ]
                }
            ]
        }
    ]

    mapper = {
        "1": "contacts",
        "1bis": "contact",
        "2": "name",
        "3": "phone",
        "4": "title"
    }

    data = json_input_to_form_format(json_input, mapper, key_name="prop")

    # Remove the intermediate property 'contact'
    b = data["contacts"]
    c = [b[0]['contact'], b[1]['contact']]
    data['contacts'] = c

    content = {
        "title": "Business Contacts",
        "contacts": [
            {"name": "Rafael", "phone": "079 000 00 00"},
            {"name": "Cyril", "phone": "079 111 11 11"},
        ]
    }

    data.__eq__(content)

    address_book = AddressBook(**data)

```

**Comment by cyrlop** [comment]
Thanks for your input @molitoris 
This issue was originally about your solution n°2 (only adapt `json_input_to_form_format`) but the solution number n°1 (remove property_1bis everywhere) would make a lot of stuff easier.
However, solution n°1 will break a lot of stuff right? Here are the things I can think of that will break/change:
    
- The way we use the Study API from the outside (no problem)
- `api_utils.py` > `json_input_to_form_format`
- `api_utils.py` > `json_entry_to_obj`
- `api_utils.py` > `StudyEntry.form_format`
- The problem is not only for FieldList of FormFields but for FieldLists in general (like FieldList of StringFields)
- **MAYBE THE BIGGEST PROBLEM:** Will it break the dynamic forms and the JSON parser from JSON to WTForm? The intermediate properties are used here right? That might be the whole reason behind them.

At the moment, it's very normalized, an entry "value" is one of the following:

- a simple value: str or bool
- a list of entries (dict) (from FieldList and FormField)
    - FieldLists has the intermediate entry

If we make this change, then a "value" could be:

- a simple value: str or bool
- a list of simple values (FieldList of simple fields)
- a list of list of entries (FieldList of FormFields)
- a list of entries (FormField)

Does it make sense? Is it possible without breaking the whole logic?

In your example below, I'm sure `address_book = AddressBook(**data)` didn't throw an error but did you make sure the data was populated inside? I would rather do:
```python
address_book = AddressBook()
address_book.process(data=data)
```

**Comment by cyrlop** [comment]
What was agreed today is to support the following formats:
```python
# 1) Simple value (v = str, bool, int, float)
{
    "property": p1,
    "value": v
}

# 2) FieldList of Simple values
{
    "property": p1,
    "value": [v, v, v]
}

# 3) FormField
{
    "property": p1,
    "value": [
        {"property": p21, "value": v},
        {"property": p22, "value": v}
    ]
}

# 4) FieldList of FormFields
{
    "prop": p1,
    "value": [
        [
	        {"property": p21, "value": v},
	        {"property": p22, "value": v}
        ],
        [
	        {"property": p21, "value": v},
	        {"property": p22, "value": v}
        ]
    ],
}
```
